extensions:

  #main menu items
  pim-free-trial-menu-entities:
    module: pim/menu/tab
    parent: pim-menu
    position: 31
    targetZone: mainMenu
    feature: free_trial
    config:
      title: free_trial.menu.entities
      icon: EntityIcon
      disabled: true

  pim-free-trial-menu-assets:
    module: pim/menu/tab
    parent: pim-menu
    position: 32
    targetZone: mainMenu
    feature: free_trial
    config:
      title: free_trial.menu.assets
      icon: AssetsIcon
      disabled: true

  #activity sub menu > proposals
  pim-free-trial-activity-submenu-proposals:
    module: pim/menu/item
    parent: pim-menu-activity-navigation-block
    position: 104
    config:
      title: free_trial.menu.proposals
      disabled: true

  #System sub menu > SSO
  pim-free-trial-system-submenu-sso:
    module: pim/menu/item
    parent: pim-menu-system-navigation-block
    position: 125
    config:
      title: free_trial.menu.sso
      disabled: true
