Akeneo\Pim\Automation\IdentifierGenerator\Application\Create\CreateGeneratorCommand:
    constraints:
        - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\IdentifierGeneratorCreationLimit:
              limit: 1
    properties:
        target:
            - NotBlank: ~
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldExist: ~
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldBeAnIdentifier: ~
        structure:
            - NotBlank: ~
            - All:
                - Collection:
                    fields:
                        type:
                            - Choice:
                                choices: ['free_text', 'auto_number']
                                message: 'Type {{ value }} can only be one of the following: {{ choices }}'
                    allowExtraFields: true
        code:
            - NotBlank: ~
            - Length:
                max: 100
        labels:
            - Count:
                  min: 1
            - All:
                - Length:
                      max: 255

Akeneo\Pim\Automation\IdentifierGenerator\Application\Update\UpdateGeneratorCommand:
    properties:
        target:
            - NotBlank: ~
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldExist: ~
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldBeAnIdentifier: ~
        structure:
            - NotBlank: ~
            - All:
                  - Collection:
                        fields:
                            type:
                                - Choice:
                                      choices: ['free_text', 'auto_number']
                                      message: 'Type {{ value }} can only be one of the following: {{ choices }}'
                        allowExtraFields: true
