Akeneo\Pim\Automation\IdentifierGenerator\Application\Create\CreateGeneratorCommand:
    constraints:
        - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\IdentifierGeneratorCreationLimit:
            limit: 1
    properties:
        target:
            - NotBlank: ~
            - Type: string
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldExist: ~
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldBeAnIdentifier: ~
        structure:
            - NotBlank: ~
            - Count:
                  max: 20
            - Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\StructureShouldNotContainMultipleAutoNumber: ~
            - All:
                - Collection:
                    fields:
                        type:
                            - Choice:
                                choices: ['free_text', 'auto_number']
                                message: 'Type {{ value }} can only be one of the following: {{ choices }}'
                        string:
                            -   Optional:
                                -   NotBlank: ~
                                -   Length:
                                        max: 100
                                - Type: string
                        numberMin:
                            -   Optional:
                                -   PositiveOrZero: ~
                        digitsMin:
                            -   Optional:
                                -   Positive: ~
                                -   LessThan: 15
        code:
            - NotBlank: ~
            - Length:
                max: 100
            - Regex:
                pattern: /^[a-zA-Z0-9_]+$/
                message: code may contain only letters, numbers and underscore
        labels:
            - All:
                - Length:
                    max: 255
        delimiter:
            - NotBlank:
                allowNull: true
            - Length:
                max: 100
