services:
    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Symfony\Command\LaunchEvaluationsCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@akeneo_batch_queue.manager.job_execution_manager'
            - '@akeneo_batch.job_repository'
            - '@logger'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\FeatureFlag\DataQualityInsightsFeature'
            - '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Symfony\Command\SchedulePeriodicTasksCommand:
        arguments:
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Connector\JobLauncher\SchedulePeriodicTasks'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\FeatureFlag\DataQualityInsightsFeature'
        tags:
            - { name: 'console.command' }
