services:

    akeneo.pim.automation.data_quality_insights.query.get_product_criteria_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetCriteriaEvaluationsByProductIdQuery
        arguments:
            - '@database_connection'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Clock\SystemClock'
            - '%akeneo.pim.automation.data_quality_insights.persistence.product_criterion_evaluation_table%'

    akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetCriteriaEvaluationsByProductIdQuery
        arguments:
            - '@database_connection'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Clock\SystemClock'
            - '%akeneo.pim.automation.data_quality_insights.persistence.product_model_criterion_evaluation_table%'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Structure\CachedGetLocalesByChannelQuery:
        arguments:
            - '@database_connection'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateProductEvaluationQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_up_to_date_product_criteria_evaluations'
            - '@akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_axes_rates'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Application\ProductEvaluation\AxisRegistry'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_model_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateProductEvaluationQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_up_to_date_product_model_criteria_evaluations'
            - '@akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_model_axes_rates'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Application\ProductEvaluation\AxisRegistry'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_product_criteria_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateCriteriaEvaluationsByProductIdQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_product_criteria_evaluations'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductEvaluationQuery'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_product_model_criteria_evaluations:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateCriteriaEvaluationsByProductIdQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductModelEvaluationQuery'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_axes_rates:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateLatestAxesRatesQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_latest_product_axes_rates'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductEvaluationQuery'

    akeneo.pim.automation.data_quality_insights.query.get_up_to_date_latest_product_model_axes_rates:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateLatestAxesRatesQuery
        arguments:
            - '@akeneo.pim.automation.data_quality_insights.query.get_latest_product_model_axes_rates'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductModelEvaluationQuery'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductEvaluationQuery:
        arguments:
            - '@database_connection'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\HasUpToDateProductModelEvaluationQuery:
        arguments:
            - '@database_connection'

    akeneo.pim.automation.data_quality_insights.query.get_latest_product_axes_rates:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetLatestAxesRatesQuery
        arguments:
            - '@database_connection'
            - 'pimee_data_quality_insights_product_axis_rates'

    akeneo.pim.automation.data_quality_insights.query.get_latest_product_model_axes_rates:
        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetLatestAxesRatesQuery
        arguments:
            - '@database_connection'
            - 'pimee_data_quality_insights_product_model_axis_rates'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Dashboard\GetDashboardRatesQuery:
        arguments:
            - '@database_connection'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Dashboard\GetAverageRanksQuery:
        arguments:
            - '@database_connection'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Dashboard\GetRanksDistributionFromProductAxisRatesQuery:
        arguments:
            - '@database_connection'
            - '@Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Structure\GetCategoryChildrenIdsQuery'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Structure\GetCategoryChildrenIdsQuery:
        arguments:
            - '@database_connection'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Structure\GetAllFamilyCodesQuery:
        arguments:
            - '@database_connection'

    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\Structure\GetAllCategoryCodesQuery:
        arguments:
            - '@database_connection'
