version: 2.1

orbs:
    slack: circleci/slack@3.4.2
    pull-up: akeneo-orbs/pull-up@1.0

aliases:
    - &slack-fail-post-step
        post-steps:
            - slack/status:
                  channel: ci
                  webhook: $SLACK_NIGHTLY_STATUS
                  fail_only: true

    - &slack-post-step
        post-steps:
            - slack/status:
                  channel: ci
                  webhook: $SLACK_NIGHTLY_STATUS
                  fail_only: false

workflows:
    version: 2

    nightly:
        when:
            and:
                - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
                - equal: [ "nightly_v6", << pipeline.schedule.name >> ]
        jobs:
            - checkout_ce
            - build_dev:
                  <<: *slack-fail-post-step
                  is_ee_built: false
                  requires:
                      - checkout_ce
            - test_back_static_and_acceptance:
                  <<: *slack-fail-post-step
                  requires:
                      - build_dev
            - test_front_static_acceptance_and_integration:
                  <<: *slack-fail-post-step
                  requires:
                      - build_dev
            - test_back_phpunit:
                  <<: *slack-fail-post-step
                  requires:
                      - build_dev
            - test_back_behat_legacy:
                  <<: *slack-fail-post-step
                  requires:
                      - build_dev
            - test_back_data_migrations:
                  <<: *slack-fail-post-step
                  requires:
                      - build_dev
    pull_up:
        jobs:
            - pull-up/pull-up:
                from: "6.0"
                into: "master"
                branch_prefix: "60_to_master"
                checkout_ours: 'src/Akeneo/Platform/EnterpriseVersion.php **/translations/*.yml'
                github_token: MICHEL_TAG_TOKEN
                github_username: "micheltag"
                slack_webhook: "${SLACK_URL_PULL_UP}"
                filters:
                    branches:
                        only:
                            - "6.0"
