version: 2.1

orbs:
    slack: circleci/slack@3.4.2

aliases:
    - &slack-fail-post-step
        post-steps:
            - slack/status:
                  channel: ci
                  webhook: $SLACK_NIGHTLY_STATUS
                  fail_only: true

workflows:
    version: 2

    on_demand:
        when:
            not:
                equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        jobs:
            - ready_to_build?:
                  type: approval
                  filters:
                      branches:
                          only: master
            - checkout_ce:
                  requires:
                      - ready_to_build?
            - build_dev:
                  is_ee_built: false
                  requires:
                      - checkout_ce
            - test_back_static_and_acceptance:
                  requires:
                      - build_dev
            - test_front_static_acceptance_and_integration:
                  requires:
                      - build_dev
            - test_back_phpunit:
                  requires:
                      - build_dev
            - test_back_behat_legacy:
                  requires:
                      - build_dev
            - test_back_data_migrations:
                  requires:
                      - build_dev
