search_event_subscription_logs:
    path: '/search-event-subscription-logs'
    controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\EventsApiDebug\SearchEventSubscriptionLogsAction
    methods: [ GET ]
    requirements:
        connection_code: '[a-zA-Z0-9_]+'

download_event_subscription_logs:
    path: '/download-event-subscription-logs'
    controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\EventsApiDebug\DownloadEventSubscriptionLogsAction
    methods: [ GET ]
    requirements:
        connection_code: '[a-zA-Z0-9_]+'
