regenerate_secret:
  path: '/{code}/webhook/regenerate-secret'
  controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Webhook\RegenerateSecretAction
  methods: [GET]
  requirements:
    code: '[a-zA-Z0-9_]+'

get:
  path: '/{code}/webhook'
  controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Webhook\GetWebhookAction
  methods: [GET]
  requirements:
    code: '[a-zA-Z0-9_]+'
    
check_reachability:
  path: '/{code}/webhook/check-reachability'
  controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Webhook\CheckWebhookReachabilityAction

update:
  path: '/{code}/webhook'
  controller: Akeneo\Connectivity\Connection\Infrastructure\InternalApi\Controller\Webhook\UpdateWebhookAction
  methods: [POST]
  requirements:
    code: '[a-zA-Z0-9_]+'
