akeneo_feature_flag:
    feature_flags:
        - { feature: 'quantified_associations', service: 'pim_structure.feature.quantified_association' }
        - { feature: 'data_quality_insights', service: 'akeneo.pim.automation.data_quality_insights.feature' }
        - { feature: 'new_shared_catalog_branding', service: 'akeneo.shared_catalog.feature.new_shared_catalog_branding' }
