framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~

            catalogs.command.bus:
                middleware:
                    - validation
            catalogs.query.bus:
                middleware:
                    - validation
