services:
    Akeneo\Connectivity\Connection\Infrastructure\Connections\Command\CreateConnectionCommand:
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Settings\Command\CreateConnectionHandler'
            - '@translator'
        tags:
            - { name: 'console.command' }

    Akeneo\Connectivity\Connection\Infrastructure\Connections\Command\PopulateAccessTokenCommand:
        arguments:
            - '@fos_oauth_server.client_manager.default'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Service\User\CreateUser'
            - '@database_connection'
        tags:
            - { name: 'console.command' }

