Akeneo\Pim\Enrichment\Component\Product\Model\QuantifiedAssociation\QuantifiedAssociations:
    constraints:
        - Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\QuantifiedAssociations: ~
