
services:

  pim_catalog.query.descendant_product_ids:
        class: Pim\Bundle\CatalogBundle\Doctrine\ORM\Query\DescendantProductIdsQuery
        arguments:
            - '@database_connection'

    pim_catalog.query.descendant_product_model_ids:
        class: Pim\Bundle\CatalogBundle\Doctrine\ORM\Query\DescendantProductModelIdsQuery
        arguments:
            - '@database_connection'
