services:
    Akeneo\Connectivity\Connection\Infrastructure\Webhook\Controller\Internal\GetWebhookAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Webhook\Query\GetAConnectionWebhookHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Webhook\Controller\Internal\RegenerateSecretAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Webhook\Command\GenerateWebhookSecretHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Webhook\Controller\Internal\CheckWebhookReachabilityAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Webhook\Command\CheckWebhookReachabilityHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Webhook\Controller\Internal\UpdateWebhookAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Webhook\Command\UpdateWebhookHandler'
            - '@oro_security.security_facade'
