services:
    Akeneo\Connectivity\Connection\Application\Webhook\Command\CheckWebhookReachabilityHandler:
        arguments:
            - '@akeneo_connectivity.connection.webhook.service.url_reachability_checker'

    Akeneo\Connectivity\Connection\Application\Webhook\Query\GetAConnectionWebhookHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\DbalGetAConnectionWebhookQuery'
            - '%webhook_active_event_subscriptions_limit%'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\DbalCountActiveEventSubscriptionsQuery'

    Akeneo\Connectivity\Connection\Application\Webhook\Command\SendBusinessEventToWebhooksHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\DbalSelectActiveWebhooksQuery'
            - '@akeneo_connectivity.connection.webhook.webhook_user_authenticator'
            - '@akeneo_connectivity.connection.webhook.webhook_client'
            - '@akeneo_connectivity.connection.webhook.webhook_event_builder'
            - '@monolog.logger.event_api'
            - '@akeneo_connectivity.connection.webhook.events_api_debug_logger'
            - '%env(AKENEO_PIM_URL)%'

    Akeneo\Connectivity\Connection\Application\Webhook\Command\UpdateWebhookHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\UpdateConnectionWebhookQuery'
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\DbalSelectWebhookSecretQuery'
            - '@Akeneo\Connectivity\Connection\Application\Webhook\Command\GenerateWebhookSecretHandler'

    Akeneo\Connectivity\Connection\Application\Webhook\Command\GenerateWebhookSecretHandler:
        arguments:
            - '@akeneo_connectivity.connection.webhook.generate_secret'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Webhook\Persistence\DbalSaveWebhookSecretQuery'
