framework:
    test: ~

pim_import_export:
    record_mails: true

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        console:
            type:  console

akeneo_pim_structure:
    reference_data:
        fabrics:
            class: Acme\Bundle\AppBundle\Entity\Fabric
            type: multi
        color:
            class: Acme\Bundle\AppBundle\Entity\Color
            type: simple
