services:
    Akeneo\Platform\Job\Infrastructure\Symfony\Command\UpdateJobFieldsToBeNotNullCommand:
        arguments:
            - '@database_connection'
        tags:
            - { name: 'console.command' }
