services:
    Akeneo\Platform\Job\Domain\Query\CountJobExecutionQueryInterface:
        class: Akeneo\Platform\Job\Infrastructure\Query\CountJobExecutionQuery
        arguments:
            - '@database_connection'

    Akeneo\Platform\Job\Application\SearchJobExecution\SearchJobExecutionInterface:
        class: Akeneo\Platform\Job\Infrastructure\Query\SearchJobExecution
        arguments:
            - '@database_connection'
