services:
    Akeneo\Platform\Job\Application\SearchJobExecution\SearchJobExecutionHandler:
        arguments:
            - '@Akeneo\Platform\Job\Application\SearchJobExecution\SearchJobExecutionInterface'
