framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler:
        collect: false

swiftmailer:
    disable_delivery: true

pim_import_export:
    record_mails: true

parameters:
    installer_data: PimInstallerBundle:minimal
