services:
    # CONTROLLERS
    ## INTERNAL
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetAppActivateUrlAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace.get_app_query'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider'
            - '@akeneo_connectivity.connection.marketplace.app_url_generator'
            - '@oro_security.security_facade'
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\IsConnectionsNumberLimitReachedQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\ConfirmAuthorizationAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\CreateAppWithAuthorizationHandler'
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Normalizer\ViolationListNormalizer'
            - '@oro_security.security_facade'
            - '@logger'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\RedirectUriWithAuthorizationCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ConnectedPimUserProvider'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\ConsentAppAuthenticationHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\ConfirmAuthenticationAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\RedirectUriWithAuthorizationCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ConnectedPimUserProvider'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\ConsentAppAuthenticationHandler'
            - '@logger'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Normalizer\ViolationListNormalizer'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetAllConnectedAppsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindAllConnectedAppsQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetConnectedAppAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindOneConnectedAppByConnectionCodeQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetAllConnectedAppScopeMessagesAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindOneConnectedAppByConnectionCodeQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ScopeMapperRegistry'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\DeleteAppAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindOneConnectedAppByConnectionCodeQuery'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\DeleteAppHandler'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetConnectedAppMonitoringSettingsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@oro_security.security_facade'
            - '@akeneo_connectivity.connection.application.handler.find_a_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\UpdateConnectedAppMonitoringSettingsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@oro_security.security_facade'
            - '@akeneo_connectivity.connection.application.handler.find_a_connection'
            - '@akeneo_connectivity.connection.application.handler.update_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Internal\GetWizardDataAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace.get_app_query'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ScopeMapperRegistry'

    ## PUBLIC
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Public\AuthorizeAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthorizationHandler'
            - '@router'
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\RedirectUriWithAuthorizationCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ConnectedPimUserProvider'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthenticationHandler'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Public\RequestAccessTokenAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace_activate.feature'
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\CreateAccessToken'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Controller\Public\GetOpenIdPublicKeyAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAsymmetricKeysQuery'

    # COMMANDS
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Command\CreateOpenIdKeysCommand:
        arguments:
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\GenerateAsymmetricKeysHandler'
        tags:
            - { name: 'console.command' }

    # VALIDATORS
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Validation\ClientIdMustBeValidValidator:
        arguments:
            - '@fos_oauth_server.client_manager.default'
        tags:
            - { name: validator.constraint_validator }

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Validation\AuthorizationCodeMustBeValidValidator:
        arguments:
            - '@fos_oauth_server.storage.default'
        tags:
            - { name: validator.constraint_validator }

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Validation\ClientIdMustHaveOngoingAuthorizationValidator:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
        tags:
            - { name: validator.constraint_validator }

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Validation\CodeChallengeMustBeValidValidator:
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\GetTestAppQuery'
            - '@akeneo_connectivity.connection.marketplace_fake_apps.feature'
        tags:
            - { name: validator.constraint_validator }

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Validation\UserIdMustBeValidValidator:
        arguments:
            - '@pim_user.repository.user'
        tags:
            - { name: validator.constraint_validator }

    # COMMANDS
    Akeneo\Connectivity\Connection\Application\Apps\Command\CreateAppWithAuthorizationHandler:
        arguments:
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@akeneo_connectivity.connection.marketplace.get_app_query'
            - '@akeneo_connectivity.connection.service.user.create_user'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\User\CreateUserGroup'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Service\CreateConnection'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\AppRoleWithScopesFactory'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Service\CreateConnectedApp'

    Akeneo\Connectivity\Connection\Application\Apps\Command\ConsentAppAuthenticationHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\CreateUserConsentQuery'
            - '@akeneo_connectivity.connection.clock'
            - '@validator'

    Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthorizationHandler:
        arguments:
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ScopeMapperRegistry'
            - '@akeneo_connectivity.connection.marketplace.get_app_query'

    Akeneo\Connectivity\Connection\Application\Apps\Command\GenerateAsymmetricKeysHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\AsymmetricKeysGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\SaveAsymmetricKeysQuery'

    Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthenticationHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetUserConsentedAuthenticationScopesQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\CreateUserConsentQuery'
            - '@akeneo_connectivity.connection.clock'
            - '@validator'

    Akeneo\Connectivity\Connection\Application\Apps\Command\DeleteAppHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppDeletionQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\DeleteConnectedAppQuery'
            - '@akeneo_connectivity.connection.persistence.repository.connection'
            - '@akeneo_connectivity.connection.service.user.delete_user'
            - '@akeneo_connectivity.connection.service.client.delete_client'
            - '@Akeneo\Connectivity\Connection\Infrastructure\User\Internal\DeleteUserGroup'
            - '@Akeneo\Connectivity\Connection\Infrastructure\User\Internal\DeleteUserRole'

    # OAUTH
    Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\AuthorizationCodeGenerator:
        arguments:
            - '@fos_oauth_server.client_manager.default'
            - '@pim_user.repository.user'
            - '@fos_oauth_server.storage.default'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Service\RandomCodeGenerator'
            - '@akeneo_connectivity.connection.clock'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\RedirectUriWithAuthorizationCodeGenerator:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\AuthorizationCodeGenerator'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\CreateAccessToken:
        arguments:
            - '@fos_oauth_server.storage.default'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Service\RandomCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery'
            - '@pim_user.repository.user'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\CreateJsonWebToken'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetConnectedAppScopesQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetUserConsentedAuthenticationUuidQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetUserConsentedAuthenticationScopesQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAccessTokenQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\CreateJsonWebToken:
        arguments:
            - '@akeneo_connectivity.connection.clock'
            - '@pim_framework.service.pim_url'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAsymmetricKeysQuery'

    # SECURITY
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ConnectedPimUserProvider:
        arguments:
            - '@security.token_storage'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ScopeMapperRegistry:
        arguments:
            - !tagged_iterator pim_api.security.scope_mapper

    # QUERIES
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAllConnectedAppsPublicIdsQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppConfirmationQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\DeleteConnectedAppQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAppDeletionQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetConnectedAppScopesQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetUserConsentedAuthenticationScopesQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetUserConsentedAuthenticationUuidQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\CreateUserConsentQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAsymmetricKeysQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\SaveAsymmetricKeysQuery:
        arguments:
            - '@database_connection'
            - '@akeneo_connectivity.connection.clock'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAccessTokenQuery:
        arguments:
            - '@database_connection'
            -
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\CreateConnectedAppQuery:
        arguments:
            - '@database_connection'
            -
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindAllConnectedAppsQuery:
        arguments:
            - '@database_connection'
            -
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindOneConnectedAppByConnectionCodeQuery:
        arguments:
            - '@database_connection'
            -
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\FindOneConnectedAppByIdQuery:
        arguments:
            - '@database_connection'

    # SERVICES
    Akeneo\Connectivity\Connection\Application\Apps\Service\CreateConnectedApp:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\CreateConnectedAppQuery'

    Akeneo\Connectivity\Connection\Application\Apps\Service\CreateConnection:
        arguments:
            - '@akeneo_connectivity.connection.persistence.repository.connection'
            - '@akeneo_connectivity.connection.persistence.query.select_connection_with_credentials_by_code'

    # OTHERS
    Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider:
        arguments:
            - '@fos_oauth_server.client_manager.default'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession:
        arguments:
            - '@session'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\AppRoleWithScopesFactory:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Security\ScopeMapperRegistry'
            - '@pim_user.factory.role'
            - '@pim_user.saver.role_with_permissions'
        public: true

    Akeneo\Connectivity\Connection\Infrastructure\Apps\AsymmetricKeysGenerator:
        public: true

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Normalizer\ViolationListNormalizer: ~

    Akeneo\Connectivity\Connection\Infrastructure\Apps\User\CreateUserGroup:
        arguments:
            - '@pim_user.factory.group'
            - '@pim_user.updater.group'
            - '@pim_user.saver.group'
            - '@validator'
