services:
    akeneo_connectivity.connection.service.apps.client_provider:
        class: Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider
        arguments:
            - '@fos_oauth_server.client_manager.default'

    Akeneo\Tool\Bundle\ApiBundle\Security\ScopeToAclMapper: ~
