services:
    akeneo_connectivity.connection.service.apps.client_provider:
        class: Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider
        arguments:
            - '@fos_oauth_server.client_manager.default'

    Akeneo\Tool\Bundle\ApiBundle\Security\ScopeToAclMapper: ~

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession:
        arguments:
            - '@session'

    Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthorizationHandler:
        arguments:
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'

    akeneo_connectivity.connection.service.apps.scope_to_view_message_mapper:
        class: Akeneo\Connectivity\Connection\Infrastructure\Apps\Mapper\ScopeToViewMessageMapper
        arguments:
            - '@Akeneo\Tool\Bundle\ApiBundle\Security\ScopeToAclMapper'
