services:
    akeneo_connectivity.connection.install.assets_installer:
        class: Akeneo\Connectivity\Connection\Infrastructure\Install\FileSystemAssetsInstaller
        arguments:
            - '@filesystem'
            - '%kernel.project_dir%'

    akeneo_connectivity.connection.install.install_subscriber:
        class: Akeneo\Connectivity\Connection\Infrastructure\Install\InstallSubscriber
        arguments:
            - '@akeneo_connectivity.connection.install.assets_installer'
            - '@database_connection'
        tags:
            - { name: kernel.event_subscriber }

    Akeneo\Connectivity\Connection\Infrastructure\Install\MigrateAudit40Master:
        class: Akeneo\Connectivity\Connection\Infrastructure\Install\MigrateAudit40Master
        arguments:
            - '@database_connection'
            - '@akeneo_connectivity.connection.application.audit.handler.update_product_event_count'
