parameters:
    akeneo_pim_marketplace_url: 'https://marketplace.akeneo.com'

services:
    akeneo_connectivity.connection.marketplace.url_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\MarketplaceUrlGenerator
        arguments:
          - '%akeneo_pim_marketplace_url%'
          - '@pim_catalog.version_provider'
          - '%env(AKENEO_PIM_URL)%'
