parameters:
    akeneo_pim_marketplace_url: 'https://marketplace.akeneo.com'
    akeneo_pim_marketplace_api_pagination_size: 100

services:
    # CONTROLLERS
    ## INTERNAL
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Controller\Internal\GetWebMarketplaceUrlAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace.url_generator'
            - '@pim_user.context.user'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Controller\Internal\GetAllExtensionsAction:
        public: true
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllExtensionsQuery'
            - '@akeneo_connectivity.connection.marketplace.analytics_generator'
            - '@pim_user.context.user'
            - '@logger'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Controller\Internal\GetAllAppsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.marketplace.app_url_generator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllAppsQuery'
            - '@akeneo_connectivity.connection.marketplace.analytics_generator'
            - '@pim_user.context.user'
            - '@logger'
            - '@akeneo_connectivity.connection.marketplace_activate.feature'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Controller\Internal\GetAllTestAppsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@akeneo_connectivity.connection.marketplace.app_url_generator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllTestAppsQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Controller\Internal\CreateTestAppsAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@validator'
            - '@security.token_storage'
            - '@Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\CreateTestAppCommandHandler'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppSecretQuery'
            - '@oro_security.security_facade'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Controller\Internal\DeleteTestAppAction:
        public: true
        arguments:
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@oro_security.security_facade'
            - '@Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\DeleteTestAppHandler'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppQuery'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\DeleteAppHandler'

    # OTHERS
    akeneo_connectivity.connection.marketplace.url_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\MarketplaceUrlGenerator
        arguments:
            - '%akeneo_pim_marketplace_url%'
            - '@pim_catalog.version_provider'
            - '%env(AKENEO_PIM_URL)%'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetUserProfileQuery'

    akeneo_connectivity.connection.marketplace.analytics_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\MarketplaceAnalyticsGenerator
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetUserProfileQuery'
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_aliases'
            - '@pim_framework.service.pim_url'
            -
    akeneo_connectivity.connection.marketplace.app_url_generator:
        class: Akeneo\Connectivity\Connection\Application\Marketplace\AppUrlGenerator
        arguments:
            - '@pim_framework.service.pim_url'

    akeneo_connectivity.connection.marketplace.guzzle_client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: '%akeneo_pim_marketplace_url%'
                headers: {User-Agent: ~}

    akeneo_connectivity.connection.marketplace.web_marketplace_api:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceApi
        arguments:
            - '@akeneo_connectivity.connection.marketplace.guzzle_client'
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_aliases'
            - '@logger'
            - '@akeneo_connectivity.connection.marketplace_fake_apps.feature'
        calls:
            - setFixturePath: [ '%connectivity.marketplace_fixtures_directory%' ]

    akeneo_connectivity.connection.marketplace.web_marketplace_aliases:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceAliases
        arguments:
            - '@pim_catalog.version_provider'

    # QUERIES
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetUserProfileQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllExtensionsQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllExtensionsQuery
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '%akeneo_pim_marketplace_api_pagination_size%'
            -
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllAppsQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllAppsQuery
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\GetAllConnectedAppsPublicIdsQuery'
            - '%akeneo_pim_marketplace_api_pagination_size%'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAppQuery:
        arguments:
            - '@akeneo_connectivity.connection.marketplace.web_marketplace_api'
            - '@akeneo_connectivity.connection.app_developer_mode.feature'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppQuery'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppQuery
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllTestAppsQuery:
        class: Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Persistence\GetAllTestAppsQuery
        arguments:
            - '@database_connection'

    # TestApps
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\CreateTestAppQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppSecretQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\DeleteTestAppQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\CreateTestAppCommandHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Service\RandomCodeGenerator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\CreateTestAppQuery'

    Akeneo\Connectivity\Connection\Application\Marketplace\TestApps\Command\DeleteTestAppHandler:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\GetTestAppQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Marketplace\TestApps\Persistence\DeleteTestAppQuery'
