akeneo_apps_list_rest:
    path: '/rest/apps'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:list }
    methods: [GET]

akeneo_apps_create_rest:
    path: '/rest/apps'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:create }
    methods: [POST]

akeneo_apps_get_rest:
    path: '/rest/apps/{code}'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:get }
    methods: [GET]
    requirements:
        code: '[a-zA-Z0-9_]+'

akeneo_apps_update_rest:
    path: '/rest/apps/{code}'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:update }
    methods: [POST]
    requirements:
        code: '[a-zA-Z0-9_]+'

akeneo_apps_delete_rest:
    path: '/rest/apps/{code}'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:delete }
    methods: [DELETE]
    requirements:
        code: '[a-zA-Z0-9_]+'

akeneo_apps_regenerate_secret_rest:
    path: '/rest/apps/{code}/regenerate-secret'
    defaults: { _controller: akeneo_app.internal_api.controller.connection:regenerateSecret }
    methods: [POST]
    requirements:
        code: '[a-zA-Z0-9_]+'

akeneo_apps_audit_source_apps_event:
    path: '/rest/apps/audit/source-apps-event'
    defaults: { _controller: akeneo_app.internal_api.controller.audit:sourceConnectionsEvent }
    methods: [GET]
    requirements:
        event_type: '[a-zA-Z_]+'
