## Frontend

# Apps Dashboard
akeneo_connectivity_connection_audit_index:
    path: '/apps/dashboard'

akeneo_connectivity_connection_audit_any:
    path: '/apps/dashboard/{any}'
    requirements:
        any: .*

# Apps
akeneo_connectivity_connection_settings_index:
   path: '/apps'

akeneo_connectivity_connection_settings_any:
    path: '/apps/{any}'
    requirements:
        any: .*
