services:
    feature_flags:
        public: true
        class: 'Akeneo\Platform\Bundle\FeatureFlagBundle\Internal\InMemoryFeatureFlags'
        arguments:
            - '@akeneo.feature_flag.service.registry'
