akeneo_catalogs_internal_get_catalogs_by_owner:
    path: '/rest/catalogs'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAllCatalogsByOwnerAction
    methods: [ GET ]

akeneo_catalogs_internal_get_catalog:
    path: '/rest/catalogs/{catalogId}'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\GetCatalogAction
    methods: [ GET ]
    requirements:
        catalogId: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

akeneo_catalogs_internal_update_catalog:
    path: '/rest/catalogs/{catalogId}'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\UpdateCatalogAction
    methods: [ PATCH ]
    requirements:
        catalogId: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

akeneo_catalogs_internal_get_families:
    path: '/rest/catalogs/families'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\GetFamiliesAction
    methods: [ GET ]

akeneo_catalogs_internal_get_attributes:
    path: '/rest/catalogs/attributes'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAttributesAction
    methods: [ GET ]

akeneo_catalogs_internal_get_attribute:
    path: '/rest/catalogs/attributes/{code}'
    controller: Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAttributeAction
    methods: [ GET ]
