services:
  Akeneo\Pim\Automation\IdentifierGenerator\Application\Create\CreateGeneratorHandler:
    arguments:
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Domain\Repository\IdentifierGeneratorRepository'
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\CreateGeneratorCommandValidator'

  Akeneo\Pim\Automation\IdentifierGenerator\Application\Update\UpdateGeneratorHandler:
    arguments:
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Domain\Repository\IdentifierGeneratorRepository'
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\UpdateGeneratorCommandValidator'

  Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\Property\GenerateAutoNumberHandler:
    arguments:
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Domain\Query\GetNextIdentifierQuery'

  Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\Property\GenerateFreeTextHandler: ~

  Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\GenerateIdentifierHandler:
    arguments:
      -
        - '@Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\Property\GenerateAutoNumberHandler'
        - '@Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\Property\GenerateFreeTextHandler'
