services:
  Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Symfony\Install\InstallerSubscriber:
    arguments:
      - '@database_connection'
    tags:
      - { name: kernel.event_subscriber }

  Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Subscriber\SetIdentifiersSubscriber:
    arguments:
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Domain\Repository\IdentifierGeneratorRepository'
      - '@Akeneo\Pim\Automation\IdentifierGenerator\Application\Generate\GenerateIdentifierCommandHandler'
      - '@validator'
    tags:
      - { name: kernel.event_subscriber }
