services:
    Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldExistValidator:
        arguments:
            - '@akeneo.pim.structure.query.get_attributes'
        tags:
            - { name: validator.constraint_validator }
    Akeneo\Pim\Automation\IdentifierGenerator\Infrastructure\Validation\TargetAttributeShouldBeAnIdentifierValidator:
        arguments:
            - '@akeneo.pim.structure.query.get_attributes'
        tags:
            - { name: validator.constraint_validator }
