services:
    Akeneo\Category\Application\Enrichment\CleanCategoryDataLinkedToChannel:
        arguments:
            - '@Akeneo\Category\Application\Query\GetAllEnrichedCategoryValuesByCategoryCode'
            - '@Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues'

    Akeneo\Category\Application\Query\GetAllEnrichedCategoryValuesByCategoryCode:
        class: Akeneo\Category\Infrastructure\Storage\Sql\GetAllEnrichedCategoryValuesByCategoryCodeSql
        arguments:
            - '@database_connection'

    Akeneo\Category\Application\Storage\UpdateCategoryEnrichedValues:
        class: Akeneo\Category\Infrastructure\Storage\Sql\Update\UpdateCategoryEnrichedValuesSql
        arguments:
            - '@database_connection'
