services:
    Akeneo\Category\Infrastructure\Cli\CheckCategoryTrees\CheckCategoryTrees:
        arguments:
            - '@database_connection'
        tags:
            - { name: console.command }

    Akeneo\Category\Infrastructure\Cli\RemoveOrphanCategories\RemoveOrphanCategories:
        arguments:
            - '@database_connection'
        tags:
            - { name: console.command }
