services:
    Akeneo\Category\Domain\Query\GetOwnedCategories:
        class: Akeneo\Category\Infrastructure\Query\DummyGetOwnedCategories

    Akeneo\Category\Domain\Query\GetViewableCategories:
        class: Akeneo\Category\Infrastructure\Query\SqlGetExistingCategories
        arguments:
            - '@database_connection'

    Akeneo\Category\Domain\Query\GetCategoryCodes:
        class: Akeneo\Category\Infrastructure\Query\SqlGetCategoryCodes
        arguments:
            - '@database_connection'

    Akeneo\Category\Domain\Query\GetNonViewableCategoryCodes:
        class: Akeneo\Category\Infrastructure\Query\GetNonViewableCategoryCodes
        arguments:
            - '@Akeneo\Category\Domain\Query\GetCategoryCodes'
            - '@Akeneo\Category\Domain\Query\GetViewableCategories'
