services:
    Akeneo\Platform\Bundle\FrameworkBundle\Command\CheckUpdateRequirementsCommand:
        arguments:
            - '@akeneo_elasticsearch.registry.clients'
            - '@akeneo_elasticsearch.client_builder'
            - ['%index_hosts%']
        tags:
            - { name: console.command }

    pim_framework.service.pim_url:
        class: Akeneo\Platform\Bundle\FrameworkBundle\Service\PimUrl
        public: true
        arguments:
            - '%env(string:AKENEO_PIM_URL)%'
