oneup_flysystem:
    adapters:
        asset_storage_adapter:
            googlecloudstorage:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: 'Google\Cloud\Storage\Bucket'
                prefix: 'asset_storage'
        catalog_storage_adapter:
            awss3v3:
                client: 'Aws\S3\S3Client'
                bucket: 'catalog'
        jobs_storage_adapter:
            awss3v3:
                client: 'Aws\S3\S3Client'
                bucket: 'jobs'
        archivist_adapter:
            awss3v3:
                client: 'Aws\S3\S3Client'
                bucket: 'archive'
