parameters:
    oro_translation.controller.class: Oro\Bundle\TranslationBundle\Controller\Controller

services:
    oro_translation.controller:
        class: '%oro_translation.controller.class%'
        arguments: ['@translator', '@templating', 'OroTranslationBundle:Translation:translation.js.twig', '']

    Oro\Bundle\TranslationBundle\Command\OroTranslationDumpCommand:
        arguments:
            - '@oro_translation.controller'
            - '@filesystem'
            - '@router'
            - '%oro_translation.js_translation.domains%'
            - '%kernel.root_dir%'
            - '%kernel.default_locale%'
        tags:
            - { name: console.command }

    Akeneo\Pim\Enrichment\Bundle\Command\QueryHelpProductCommand:
        arguments:
            - '@pim_catalog.query.filter.product.field_dumper'
            - '@pim_catalog.query.filter.product.attribute_dumper'
        tags:
            - { name: console.command }