services:
    Akeneo\Connectivity\Connection\Infrastructure\Marketplace\Install\InstallSubscriber:
        arguments:
            - '@database_connection'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\GenerateAsymmetricKeysHandler'
            - '@Akeneo\Connectivity\Connection\Application\Apps\Command\AddAclToRolesHandler'
        tags:
            - {name: kernel.event_subscriber}
