services:
    Akeneo\Connectivity\Connection\Infrastructure\ErrorManagement\EventSubscriber\ApiErrorEventSubscriber:
        arguments:
            - '@akeneo_connectivity.connection.error_management.service.collect_api_error'
        tags:
            - { name: kernel.event_subscriber }
