services:
    Akeneo\Connectivity\Connection\Application\ErrorManagement\Service\CollectApiError:
        arguments:
            - '@akeneo_connectivity.connection.service.connection_context'
            - '@Akeneo\Connectivity\Connection\Infrastructure\ErrorManagement\Persistence\ElasticsearchBusinessErrorRepository'
            - '@Akeneo\Connectivity\Connection\Application\ErrorManagement\Command\UpdateConnectionErrorCountHandler'
            - '@akeneo_connectivity.connection.exception_serializer'

    akeneo_connectivity.connection.exception_serializer:
        class: FOS\RestBundle\Serializer\SymfonySerializerAdapter
        arguments:
            - '@pim_domain_error_serializer'
