services:
    akeneo.platform.command.install:
        class: 'Akeneo\Platform\Bundle\InstallerBundle\Command\InstallCommand'
        arguments:
            - '@pim_installer.install_status_manager'
        tags:
            - { name: 'console.command' }
