services:
    pim_catalog.completeness.calculator:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Completeness\CompletenessCalculator'
        arguments:
            - '@akeneo.pim.enrichment.completeness.query.get_product_masks'
            - '@akeneo.pim.structure.query.get_required_attributes_masks'

    pim_catalog.completeness.product.compute_and_persist:
        class: 'Akeneo\Pim\Enrichment\Bundle\Product\ComputeAndPersistProductCompletenesses'
        arguments:
            - '@pim_catalog.completeness.calculator'
            - '@akeneo.pim.enrichment.product.query.save_product_completenesses'
