parameters:
    pim_catalog.elasticsearch.indexer.product.class: 'Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Indexer\ProductIndexer'
    pim_catalog.elasticsearch.indexer.product_model_indexer.class: 'Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Indexer\ProductModelIndexer'
    pim_catalog.elasticsearch.indexer.product_model_descendants_indexer.class: 'Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Indexer\ProductModelDescendantsIndexer'

services:
    pim_catalog.elasticsearch.indexer.product:
        class: '%pim_catalog.elasticsearch.indexer.product.class%'
        arguments:
            - '@pim_indexing_serializer'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'
            - '@akeneo.pim.enrichment.product.query.get_product_completenesses'
            - '@pim_catalog.family_variant.provider.entity_with_family_variant_attributes'

    pim_catalog.elasticsearch.indexer.product_model:
        class: '%pim_catalog.elasticsearch.indexer.product_model_indexer.class%'
        arguments:
            - '@pim_indexing_serializer'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@pim_catalog.repository.product_model'

    pim_catalog.elasticsearch.indexer.product_model_descendance:
        class: '%pim_catalog.elasticsearch.indexer.product_model_descendants_indexer.class%'
        arguments:
            - '@pim_catalog.elasticsearch.indexer.product'
            - '@pim_catalog.elasticsearch.indexer.product_model'
