services:
    Akeneo\Pim\Enrichment\Component\Product\Command\ProductModel\RemoveProductModelHandler:
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.remover.product_model'
            - '@akeneo_elasticsearch.client.product_and_product_model'
