Akeneo\Connectivity\Connection\Domain\Webhook\Model\Write\ConnectionWebhook:
  constraints:
      - Akeneo\Connectivity\Connection\Application\Webhook\Validation\EnabledWebhookRequiresAnUrl: ~
  properties:
    url:
      - Url: ~
