services:
    AppCommand:
        class: Akeneo\Apps\Infrastructure\Cli\AppCommand
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
            - '@akeneo_app.application.handler.regenerate_app_secret'
        tags:
            - { name: 'console.command' }

    DeleteAppCommand:
        class: Akeneo\Apps\Infrastructure\Cli\DeleteAppCommand
        arguments:
            - '@akeneo_app.application.handler.delete_app'
        tags:
            - { name: 'console.command' }

    PopulateAuditTableCommand:
        class: Akeneo\Apps\Infrastructure\Cli\PopulateAuditTableCommand
        arguments:
            - '@database_connection'
            - '@akeneo_app.application.handler.fetch_apps'
            - '@akeneo_app.application.audit.handler.count_daily_events_by_app'
        tags:
            - { name: 'console.command' }
