services:
    AppCommand:
        class: Akeneo\Apps\Infrastructure\Cli\AppCommand
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
        tags:
            - { name: 'console.command' }
