services:
    akeneo_app.internal_api.controller.app:
        class: 'Akeneo\Apps\Infrastructure\InternalApi\Controller\AppController'
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
