services:
    akeneo_app.internal_api.controller.app:
        public: true
        class: 'Akeneo\Apps\Infrastructure\InternalApi\Controller\AppController'
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
            - '@akeneo_app.application.handler.find_an_app'
            - '@akeneo_app.application.handler.update_app'
            - '@akeneo_app.application.handler.delete_app'
            - '@akeneo_app.application.handler.regenerate_app_secret'
            - '@oro_security.security_facade'

    akeneo_app.internal_api.controller.audit:
        public: true
        class: 'Akeneo\Apps\Infrastructure\InternalApi\Controller\AuditController'
        arguments:
            - '@akeneo_app.application.audit.handler.count_daily_events_by_app'
