services:
    akeneo_app.internal_api.controller.app:
        public: true
        class: 'Akeneo\Apps\Infrastructure\InternalApi\Controller\AppController'
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
            - '@akeneo_app.application.handler.find_an_app'
            - '@oro_security.security_facade'
