extensions:
    pim-menu-system-apps:
        module: pim/menu/item
        parent: pim-menu-system-navigation-block
        position: 120
        config:
            title: pim_menu.item.apps
            to: akeneo_apps_index
