services:
    akeneo_app.application.handler.create_app:
        class: 'Akeneo\Apps\Application\Command\CreateAppHandler'
        public: true
        arguments:
            - '@validator'
            - '@akeneo_app.persistence.repository.app'
            - '@akeneo_app.service.client.create_client'
            - '@akeneo_app.service.user.create_user'

    akeneo_app.application.handler.fetch_apps:
        class: 'Akeneo\Apps\Application\Query\FetchAppsHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_apps'

    akeneo_app.application.handler.find_an_app:
        class: 'Akeneo\Apps\Application\Query\FindAnAppHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_app_with_credentials_by_code'

    akeneo_app.application.handler.update_app:
        class: 'Akeneo\Apps\Application\Command\UpdateAppHandler'
        arguments:
            - '@validator'
            - '@akeneo_app.persistence.repository.app'

    akeneo_app.application.handler.delete_app:
        class: 'Akeneo\Apps\Application\Command\DeleteAppHandler'
        arguments:
            - '@akeneo_app.persistence.repository.app'
            - '@akeneo_app.service.client.delete_client'
            - '@akeneo_app.service.user.delete_user'

    akeneo_app.application.handler.regenerate_app_secret:
        class: 'Akeneo\Apps\Application\Command\RegenerateAppSecretHandler'
        arguments:
            - '@akeneo_app.persistence.repository.app'
            - '@akeneo_app.service.client.regenerate_client_secret'

    akeneo_app.audit.application.handler.fetch_apps_event_count_by_event:
        class: 'Akeneo\Apps\Audit\Application\Query\FetchAppsEventCountByEventHandler'
        arguments:
            - '@akeneo_app.audit.persistence.query.select_apps_event_count_by_date'
