services:
    akeneo_app.application.handler.create_app:
        class: 'Akeneo\Apps\Application\Command\CreateAppHandler'
        public: true
        arguments:
            - '@validator'
            - '@akeneo_app.persistence.repository.app'
            - '@akeneo_app.service.client.create_client'
            - '@akeneo_app.service.user.create_user'

    akeneo_app.application.handler.fetch_apps:
        class: 'Akeneo\Apps\Application\Query\FetchAppsHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_apps'

    akeneo_app.application.handler.find_an_app:
        class: 'Akeneo\Apps\Application\Query\FindAnAppHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_app_and_credentials_by_code'
