services:
    akeneo_app.application.handler.create_connection:
        class: 'Akeneo\Apps\Application\Settings\Command\CreateConnectionHandler'
        public: true
        arguments:
            - '@validator'
            - '@akeneo_app.persistence.repository.connection'
            - '@akeneo_app.service.client.create_client'
            - '@akeneo_app.service.user.create_user'

    akeneo_app.application.handler.fetch_connections:
        class: 'Akeneo\Apps\Application\Settings\Query\FetchConnectionsHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_connections'

    akeneo_app.application.handler.find_a_connection:
        class: 'Akeneo\Apps\Application\Settings\Query\FindAConnectionHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_connection_with_credentials_by_code'

    akeneo_app.application.handler.update_connection:
        class: 'Akeneo\Apps\Application\Settings\Command\UpdateConnectionHandler'
        arguments:
            - '@validator'
            - '@akeneo_app.persistence.repository.connection'

    akeneo_app.application.handler.delete_connection:
        class: 'Akeneo\Apps\Application\Settings\Command\DeleteConnectionHandler'
        arguments:
            - '@akeneo_app.persistence.repository.connection'
            - '@akeneo_app.service.client.delete_client'
            - '@akeneo_app.service.user.delete_user'

    akeneo_app.application.handler.regenerate_connection_secret:
        class: 'Akeneo\Apps\Application\Settings\Command\RegenerateConnectionSecretHandler'
        arguments:
            - '@akeneo_app.persistence.repository.connection'
            - '@akeneo_app.service.client.regenerate_client_secret'

    akeneo_app.application.audit.handler.count_daily_events_by_connection:
        class: 'Akeneo\Apps\Application\Audit\Query\CountDailyEventsByConnectionHandler'
        arguments:
            - '@akeneo_app.persistence.query.select_connections_event_count_by_day'

    akeneo_app.application.audit.handler.update_product_event_count:
        class: Akeneo\Apps\Application\Audit\Command\UpdateProductEventCountHandler
        arguments:
            - '@akeneo_app.persistence.query.extract_connections_product_event_count'
            - '@akeneo_app.persistence.repository.event_count'
