services:
    akeneo_apps.install.assets_installer:
        class: Akeneo\Apps\Infrastructure\Install\FileSystemAssetsInstaller
        arguments:
            - '@filesystem'
            - '%kernel.project_dir%'

    akeneo_apps.install.install_subscriber:
        class: Akeneo\Apps\Infrastructure\Install\InstallSubscriber
        arguments:
            - '@akeneo_apps.install.assets_installer'
            - '@database_connection'
        tags:
            - { name: kernel.event_subscriber }
