services:
    Akeneo\Connectivity\Connection\Infrastructure\Audit\Command\PurgeAuditErrorCommand:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\PurgeAuditErrorQuery'
        tags:
            - {name: 'console.command'}

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Command\UpdateAuditDataCommand:
        arguments:
            - '@akeneo_connectivity.connection.application.audit.handler.update_data_source_product_event_count'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectHourlyIntervalsToRefreshQuery'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalPurgeAuditProductQuery'
        tags:
            - { name: 'console.command' }
