services:
    Akeneo\Connectivity\Connection\Infrastructure\Audit\Command\PurgeAuditErrorCommand:
        arguments:
            - '@akeneo_connectivity_connection.persistence.query.purge_audit_error'
        tags:
            - {name: 'console.command'}

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Command\UpdateAuditDataCommand:
        arguments:
            - '@akeneo_connectivity.connection.application.audit.handler.update_data_source_product_event_count'
            - '@akeneo_connectivity_connection.persistence.query.select_hourly_intervals_to_refresh'
            - '@akeneo_connectivity_connection.persistence.query.purge_audit_product'
        tags:
            - { name: 'console.command' }
