services:
    Akeneo\Connectivity\Connection\Infrastructure\Audit\EventSubscriber\ReadProductsEventSubscriber:
        arguments:
            - '@akeneo_connectivity.connection.service.connection_context'
            - '@Akeneo\Connectivity\Connection\Application\Audit\Command\UpdateDataDestinationProductEventCountHandler'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Settings\Persistence\DbalConnectionRepository'
        tags:
            - { name: kernel.event_subscriber }
