services:
    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalPurgeAuditProductQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectErrorCountPerConnectionQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectHourlyIntervalsToRefreshQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\PurgeAuditErrorQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectPeriodErrorCountPerConnectionQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectPeriodEventCountPerConnectionQuery:
        arguments:
            - '@database_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalExtractConnectionsProductEventCountQuery:
        arguments:
            - '@database_connection'
            - '%pim_catalog.entity.product.class%'

    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalSelectEventsApiRequestCountWithinLastHourQuery:
        arguments:
            - '@database_connection'

    # To split into queries
    Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\DbalEventCountRepository:
        arguments:
            - '@database_connection'
