services:
  akeneo.installer.handler.install_pim:
    class: Akeneo\Platform\Installer\Application\InstallPim\InstallPimHandler
    public: true
    arguments:
      - '@akeneo.installer.fixtures.installer'

  Akeneo\Platform\Installer\Application\ResetDatabase\ResetDatabaseHandler:
    arguments:
      - '@Akeneo\Platform\Installer\Infrastructure\Query\FindTables'
      - '@Akeneo\Platform\Installer\Infrastructure\DatabaseResetter\MySqlDatabaseResetter'
