services:
  Akeneo\Platform\Installer\Infrastructure\DatabasePurger\DbalPurger:
    arguments:
      - '@database_connection'

  Akeneo\Platform\Installer\Infrastructure\FixtureInstaller\MinimalFixtureInstaller:
    arguments:
      - '%kernel.project_dir%'

  akeneo.installer.reset_pim.feature:
    class: Akeneo\Platform\Bundle\FeatureFlagBundle\Configuration\EnvVarFeatureFlag
    arguments:
      - '%env(bool:FLAG_RESET_PIM_ENABLED)%'
    public: true
