Akeneo\Apps\Application\Settings\Command\CreateConnectionCommand:
    group_sequence:
      - CreateConnectionCommand
      - Business
    properties:
        code:
            - Callback: [Akeneo\Apps\Domain\Settings\Validation\Connection\ConnectionCodeMustBeValid, validate]
            - Akeneo\Apps\Application\Settings\Validation\Connection\CodeMustBeUnique:
                groups: [Business]
        label:
            - Callback: [Akeneo\Apps\Domain\Settings\Validation\Connection\ConnectionLabelMustBeValid, validate]
        flowType:
            - Callback: [Akeneo\Apps\Domain\Settings\Validation\Connection\FlowTypeMustBeValid, validate]
