Akeneo\Apps\Application\Command\CreateAppCommand:
    group_sequence:
      - CreateAppCommand
      - Business
    properties:
        code:
            - Callback: [Akeneo\Apps\Domain\Validation\App\AppCodeMustBeValid, validate]
            - Akeneo\Apps\Application\Validation\App\CodeMustBeUnique:
                groups: [Business]
        label:
            - Callback: [Akeneo\Apps\Domain\Validation\App\AppLabelMustBeValid, validate]
        flowType:
            - Callback: [Akeneo\Apps\Domain\Validation\App\FlowTypeMustBeValid, validate]
